apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.11
    path: /opt/data/mealie-data
  mountOptions:
    - nfsvers=4.2
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: mealie-data-pv
  storageClassName: ""
